# arxivの学問領域の指定
subject: 'cat:cs.AI OR cat:cs.HC OR cat:cs.AI'

# 検索キーワード
keywords:
        agent: 1
        robot: 1
        behavior modification: 2
        behavior change: 2
        attitude modification: 2
        interaction: 2
        emotion: 2
        character: 2

# 通知の閾値
score_threshold: 0
